/* ==========================================================================
   B1 Preliminary — the Cambridge vocabulary list as a deck.

   Cambridge publishes the list as words and parts of speech; everything a card
   needs beyond that is written here. Where Cambridge printed an example of its
   own it is kept, because it shows the sense the exam expects.

   Every card follows the same rules, and tools/check-b1.js enforces them:
     · the example contains the term as it is written on the card
     · the definition is plain English, at most 30 words, no abbreviations
     · the translation gives the 2-3 renderings Turkish actually uses
     · collocations are set phrases that contain the word — never padding
     · family members are separate dictionary words, not inflections
   ========================================================================== */
const B1_DECK = {
  name: 'B1 Preliminary',
  emoji: '🎓',
  description: 'The Cambridge B1 Preliminary vocabulary list (August 2025) — every word, with a definition, an example, a translation and its word family.',
  cards: [

    { term:'able', pos:'adjective', tags:['Language'], definition:'Having the skill, strength or opportunity to do something.',
      example:'She was able to answer every question without looking at her notes.',
      translation:'muktedir, yapabilen', collocations:['be able to'],
      related:[{kind:'ant',text:'unable'},{kind:'family',text:'ability'},{kind:'family',text:'disabled'}] },

    { term:'absolutely', pos:'adverb', definition:'Completely, or used to agree strongly with someone.',
      example:'The movie was absolutely awful.',
      translation:'kesinlikle, tamamen', collocations:['absolutely right','absolutely not'],
      related:[{kind:'syn',text:'completely'},{kind:'syn',text:'totally'},{kind:'family',text:'absolute'}] },

    { term:'accent', pos:'noun', definition:'The way someone pronounces words, showing where they come from.',
      example:'She has a beautiful French accent.',
      translation:'aksan, şive', collocations:['a strong accent','a foreign accent'],
      related:[{kind:'family',text:'accentuate'}] },

    { term:'access', pos:'noun', tags:['Communications and Technology'], definition:'The right or the means to enter a place or use something.',
      example:'The flat has easy access to the city centre.',
      translation:'erişim, giriş', collocations:['internet access','disabled access','access to'],
      related:[{kind:'family',text:'accessible'},{kind:'family',text:'accessory'}] },

    { term:'accident', pos:'noun', tags:['Health, Medicine and Exercise'], definition:'Something bad that happens without anyone planning it, often hurting someone.',
      example:'He broke his arm in a cycling accident.',
      translation:'kaza', collocations:['a car accident','by accident','have an accident'],
      related:[{kind:'family',text:'accidental'},{kind:'family',text:'accidentally'}] },

    { term:'achieve', pos:'verb', definition:'To succeed in doing something after working for it.',
      example:'She worked for years to achieve her ambition of running a restaurant.',
      translation:'başarmak, elde etmek', collocations:['achieve a goal','achieve success'],
      related:[{kind:'syn',text:'accomplish'},{kind:'family',text:'achievement'}] },

    { term:'actually', pos:'adverb', definition:'In fact, or used to correct what someone believes.',
      example:'She seems a bit strict at first, but she is actually very nice.',
      translation:'aslında, gerçekten', collocations:[],
      related:[{kind:'syn',text:'really'},{kind:'syn',text:'in fact'},{kind:'family',text:'actual'}] },

    { term:'admire', pos:'verb', definition:'To respect someone, or to look at something and enjoy how good it is.',
      example:'I admire the way she stays calm when everything goes wrong.',
      translation:'hayran olmak, takdir etmek', collocations:['admire someone for something'],
      related:[{kind:'family',text:'admiration'},{kind:'family',text:'admirable'}] },

    { term:'advice', pos:'noun', definition:'An opinion about what someone should do.',
      example:'My teacher gave me some useful advice about the exam.',
      translation:'tavsiye, öğüt', collocations:['give advice','take advice','a piece of advice'],
      related:[{kind:'family',text:'advise'},{kind:'family',text:'adviser'}],
      notes:'Uncountable: "some advice", "a piece of advice" — never "an advice" or "advices".' },

    { term:'advise', pos:'verb', definition:'To tell someone what you think they should do.',
      example:'The doctor advised him to rest for a week.',
      translation:'tavsiye etmek, öğüt vermek', collocations:['advise someone to do something','strongly advise'],
      related:[{kind:'family',text:'advice'},{kind:'family',text:'adviser'}],
      notes:'The verb is spelt with an s and the noun (advice) with a c.' },

    { term:'afford', pos:'verb', definition:'To have enough money or time for something.',
      example:'We cannot afford a holiday this year.',
      translation:'gücü yetmek, parası yetmek', collocations:['can afford','afford to do something'],
      related:[{kind:'family',text:'affordable'}],
      notes:'Almost always used with can, could or be able to.' },

    { term:'ancient', pos:'adjective', definition:'From a time thousands of years ago, or very old indeed.',
      example:'We spent the morning walking round an ancient Greek temple.',
      translation:'antik, kadim, çok eski', collocations:['ancient history','ancient ruins'],
      related:[{kind:'ant',text:'modern'}] },

    { term:'announce', pos:'verb', definition:'To tell people about something officially or publicly.',
      example:'The airline announced that the flight would be two hours late.',
      translation:'duyurmak, ilan etmek', collocations:['announce a decision'],
      related:[{kind:'family',text:'announcement'},{kind:'family',text:'announcer'}] },

    { term:'annoyed', pos:'adjective', tags:['Language'], definition:'A little angry about something.',
      example:'She was annoyed that nobody had told her about the change.',
      translation:'kızgın, sinirlenmiş, canı sıkkın', collocations:['annoyed with someone','annoyed about something'],
      related:[{kind:'syn',text:'irritated'},{kind:'family',text:'annoy'},{kind:'family',text:'annoying'}],
      notes:'Annoyed is how you feel; annoying is what causes it.' },

    { term:'answer', pos:'noun', tags:['Language'], sense:'a reply', definition:'What you say or write when someone asks you something.',
      example:'I wrote to them last month but I am still waiting for an answer.',
      translation:'cevap, yanıt, karşılık', collocations:['the right answer','give an answer'],
      related:[{kind:'syn',text:'reply'},{kind:'syn',text:'response'},{kind:'ant',text:'question'}] },

    { term:'answer', pos:'verb', tags:['Language'], sense:'to reply', definition:'To say or write something back to someone who has asked you.',
      example:'Please answer the question in your own words.',
      translation:'cevaplamak, yanıtlamak', collocations:['answer a question','answer the phone','answer the door'],
      related:[{kind:'syn',text:'reply'},{kind:'family',text:'answerphone'}] },

    { term:'apologise', pos:'verb', definition:'To say that you are sorry for something you have done.',
      example:'He apologised for arriving so late.',
      translation:'özür dilemek', collocations:['apologise for something','apologise to someone'],
      related:[{kind:'family',text:'apology'}],
      notes:'British spelling. American English writes apologize.' },

    { term:'appointment', pos:'noun', tags:['Time'], definition:'An arrangement to meet someone at a particular time.',
      example:'I have a dental appointment at four o’clock.',
      translation:'randevu', collocations:['make an appointment','a doctor’s appointment'],
      related:[{kind:'family',text:'appoint'}],
      notes:'For meeting a doctor or a client. A meeting with a friend is a date or arrangement, not an appointment.' },

    { term:'argue', pos:'verb', tags:['Language'], definition:'To disagree with someone, often angrily.',
      example:'They argue about money almost every week.',
      translation:'tartışmak, kavga etmek', collocations:['argue with someone','argue about something'],
      related:[{kind:'family',text:'argument'}] },

    { term:'arrange', pos:'verb', definition:'To plan something, or to put things in a particular order.',
      example:'Could you arrange a meeting for Thursday morning?',
      translation:'ayarlamak, düzenlemek', collocations:['arrange a meeting','arrange to meet'],
      related:[{kind:'syn',text:'organise'},{kind:'family',text:'arrangement'}] },

    { term:'at least', pos:'phrase', definition:'Not less than a number, or used to mention one good thing in a bad situation.',
      example:'It rained all week, but at least the hotel was comfortable.',
      translation:'en azından, hiç değilse', collocations:[],
      related:[{kind:'ant',text:'at most'}] },

    { term:'attend', pos:'verb', definition:'To go to an event, a class or a meeting.',
      example:'All the students must attend the first lecture.',
      translation:'katılmak, devam etmek', collocations:['attend a meeting','attend a course'],
      related:[{kind:'family',text:'attendance'}],
      notes:'More formal than go to. You attend a meeting — no preposition after it.' },

    { term:'autumn', pos:'noun', tags:['Time'], definition:'The season between summer and winter, when leaves fall.',
      example:'The forest is beautiful in autumn.',
      translation:'sonbahar, güz', collocations:['in autumn','last autumn'],
      related:[{kind:'family',text:'season'}],
      notes:'British English. American English says fall.' },

    { term:'avoid', pos:'verb', definition:'To stay away from something, or to stop something from happening.',
      example:'We left early to avoid the traffic.',
      translation:'kaçınmak, sakınmak', collocations:['avoid doing something'],
      related:[{kind:'family',text:'unavoidable'}],
      notes:'Followed by the -ing form: "avoid making mistakes", never "avoid to make".' },

    { term:'background', pos:'noun', sense:'behind', definition:'The part of a view or a picture that is furthest away.',
      example:'You can see the mountains in the background of the photo.',
      translation:'arka plan, fon', collocations:['in the background'],
      related:[{kind:'ant',text:'foreground'}] },

    { term:'background', pos:'noun', sense:'experience', definition:'Someone’s family, education and past experience.',
      example:'She has a background in engineering.',
      translation:'geçmiş, özgeçmiş, altyapı', collocations:['a background in something','family background'],
      related:[{kind:'syn',text:'experience'}] },

    { term:'bargain', pos:'noun', tags:['Shopping'], definition:'Something bought for much less than it is worth.',
      example:'At that price the bike was a real bargain.',
      translation:'kelepir, ucuzluk', collocations:['a real bargain','a bargain price'],
      related:[{kind:'syn',text:'a good deal'}] },

    { term:'belong', pos:'verb', definition:'To be owned by someone, or to be in the right place.',
      example:'These keys belong to my brother.',
      translation:'ait olmak', collocations:['belong to someone'],
      related:[{kind:'family',text:'belongings'}] },

    { term:'borrow', pos:'verb', definition:'To take something from someone and give it back later.',
      example:'Can I borrow your pen for a minute?',
      translation:'ödünç almak', collocations:['borrow money','borrow something from someone'],
      related:[{kind:'ant',text:'lend'}],
      notes:'You borrow from someone; they lend to you. The two are opposite directions.' },

    { term:'break down', pos:'phrasal verb', definition:'To stop working, used of a machine or a vehicle.',
      example:'The car has broken down.',
      translation:'bozulmak, arızalanmak', collocations:[],
      related:[{kind:'family',text:'breakdown'}] },

    { term:'brief', pos:'adjective', definition:'Lasting a short time, or using few words.',
      example:'She gave a brief description of what had happened.',
      translation:'kısa, özlü', collocations:['a brief visit','in brief'],
      related:[{kind:'syn',text:'short'},{kind:'family',text:'briefly'}] },

    { term:'bring up', pos:'phrasal verb', sense:'to raise a child', definition:'To look after a child until it is grown up.',
      example:'She was brought up in London.',
      translation:'yetiştirmek, büyütmek', collocations:[],
      related:[{kind:'syn',text:'raise'},{kind:'family',text:'upbringing'}] },

    { term:'careful', pos:'adjective', tags:['Language'], definition:'Giving attention to what you are doing so that nothing goes wrong.',
      example:'Be careful with that knife.',
      translation:'dikkatli, özenli', collocations:['be careful','careful with something'],
      related:[{kind:'ant',text:'careless'},{kind:'family',text:'care'},{kind:'family',text:'carefully'}] },

    { term:'cheap', pos:'adjective', tags:['Shopping'], definition:'Costing little money.',
      example:'We found a cheap hotel near the station.',
      translation:'ucuz, hesaplı', collocations:['a cheap flight','dirt cheap'],
      related:[{kind:'ant',text:'expensive'},{kind:'family',text:'cheaply'}] },

    { term:'cheers', pos:'exclamation', definition:'Said when raising a glass, and in British English also for thank you or goodbye.',
      example:'Cheers! Here is to your new job.',
      translation:'şerefe, sağlığına', collocations:[],
      related:[{kind:'family',text:'cheerful'}],
      notes:'Informal. In Britain it also means thanks or bye.' },

    { term:'clothes', pos:'plural noun', tags:['Clothes and Accessories'], definition:'The things people wear, such as shirts, trousers and coats.',
      example:'I need to buy some warm clothes for the winter.',
      translation:'giysiler, kıyafetler, elbiseler', collocations:['put on clothes','take off clothes'],
      related:[{kind:'family',text:'clothing'},{kind:'family',text:'cloth'}],
      notes:'Always plural: "clothes are", never "a clothes". One item is "a piece of clothing".' },

    { term:'complain', pos:'verb', tags:['Shopping'], definition:'To say that you are not happy about something.',
      example:'She complained to the manager about the noise.',
      translation:'şikayet etmek, yakınmak', collocations:['complain about something','complain to someone'],
      related:[{kind:'family',text:'complaint'}] },

    { term:'confident', pos:'adjective', tags:['Language'], definition:'Sure that you can do something well, or sure that something is true.',
      example:'He is confident that he will pass the exam.',
      translation:'kendine güvenen, emin', collocations:['confident about something','feel confident'],
      related:[{kind:'family',text:'confidence'},{kind:'ant',text:'nervous'}] },

    { term:'crowded', pos:'adjective', definition:'Full of people, with little room to move.',
      example:'The train was so crowded that we had to stand.',
      translation:'kalabalık', collocations:['a crowded street','crowded with people'],
      related:[{kind:'family',text:'crowd'}] },

    { term:'deal with', pos:'phrasal verb', definition:'To take action about a problem, or to do business with someone.',
      example:'I have had some problems to deal with.',
      translation:'ilgilenmek, halletmek, uğraşmak', collocations:['deal with a problem'],
      related:[{kind:'syn',text:'handle'}] },

    { term:'delay', pos:'noun', tags:['Travel and Transport'], definition:'A time when something happens later than it should.',
      example:'There was a long delay at the airport.',
      translation:'gecikme, rötar', collocations:['a long delay','without delay'],
      related:[{kind:'syn',text:'hold-up'},{kind:'ant',text:'punctuality'}] },

    { term:'deliver', pos:'verb', tags:['Travel and Transport'], definition:'To take goods or letters to the place where they have been sent.',
      example:'They deliver the newspaper before seven every morning.',
      translation:'teslim etmek, dağıtmak', collocations:['deliver a parcel','deliver a message'],
      related:[{kind:'family',text:'delivery'}] },

    { term:'describe', pos:'verb', definition:'To say what someone or something is like.',
      example:'Can you describe the man you saw?',
      translation:'tarif etmek, betimlemek, anlatmak', collocations:['describe something to someone'],
      related:[{kind:'family',text:'description'}] },

    { term:'disappointed', pos:'adjective', tags:['Language'], definition:'Unhappy because something was not as good as you hoped.',
      example:'We were disappointed with the hotel.',
      translation:'hayal kırıklığına uğramış', collocations:['disappointed with something','disappointed that'],
      related:[{kind:'family',text:'disappoint'},{kind:'family',text:'disappointing'},{kind:'family',text:'disappointment'}],
      notes:'You are disappointed; the thing is disappointing.' },

    { term:'discover', pos:'verb', definition:'To find something, or to learn something you did not know.',
      example:'Scientists have discovered a new kind of insect in the forest.',
      translation:'keşfetmek, bulmak', collocations:['discover that'],
      related:[{kind:'family',text:'discovery'}] },

    { term:'earn', pos:'verb', tags:['Work and Jobs'], definition:'To get money by working, or to get something by deserving it.',
      example:'She earns more than her brother.',
      translation:'kazanmak', collocations:['earn money','earn a living'],
      related:[{kind:'family',text:'earnings'}],
      notes:'Earn is for work; win is for competitions and prizes.' },

    { term:'embarrassed', pos:'adjective', tags:['Language'], definition:'Feeling uncomfortable and shy because of something you have done.',
      example:'I felt embarrassed when I forgot her name.',
      translation:'utanmış, mahcup', collocations:['embarrassed about something'],
      related:[{kind:'family',text:'embarrass'},{kind:'family',text:'embarrassing'},{kind:'family',text:'embarrassment'}] },

    { term:'encourage', pos:'verb', definition:'To give someone the confidence or the reason to do something.',
      example:'My parents encouraged me to study abroad.',
      translation:'teşvik etmek, cesaretlendirmek', collocations:['encourage someone to do something'],
      related:[{kind:'ant',text:'discourage'},{kind:'family',text:'encouragement'}] },

    { term:'environment', pos:'noun', tags:['The Natural World'], definition:'The air, water and land around us, or the conditions someone lives and works in.',
      example:'Plastic waste is doing real harm to the environment.',
      translation:'çevre, ortam', collocations:['protect the environment','a working environment'],
      related:[{kind:'family',text:'environmental'},{kind:'syn',text:'surroundings'}] },

    { term:'give up', pos:'phrasal verb', definition:'To stop doing something, especially something you did regularly.',
      example:'Has David given up playing tennis?',
      translation:'bırakmak, vazgeçmek', collocations:['give up smoking'],
      related:[{kind:'syn',text:'quit'}] },
    { term:'according to', pos:'phrase', definition:'As stated or shown by a particular person or source.',
      example:'According to the weather forecast, it will rain tomorrow.',
      translation:'göre, -e bakılırsa', collocations:['according to the plan'] },
    { term:'act', pos:'noun', tags:['Entertainment and Media'], definition:'One of the main parts that a play or an opera is divided into.',
      example:'The best song comes in the second act.',
      translation:'perde, bölüm', collocations:['the first act','the second act'],
      related:[{kind:'family',text:'actor'},{kind:'family',text:'action'}] },
    { term:'act', pos:'verb', tags:['Entertainment and Media'], definition:'To perform a part in a play or a film, or to behave in a certain way.',
      example:'She wants to act in a film one day.',
      translation:'oynamak, rol yapmak, davranmak', collocations:['act like a child'],
      related:[{kind:'family',text:'actor'},{kind:'family',text:'actress'}] },
    { term:'ad', pos:'noun', tags:['Shopping'], definition:'A short public notice that tries to sell something or announce a job.',
      example:'I saw an ad for a cheap flight to Rome.',
      translation:'reklam, ilan', collocations:['a job ad','put an ad in'],
      related:[{kind:'syn',text:'advertisement'},{kind:'family',text:'advertise'}] },
    { term:'ages', pos:'plural noun', tags:['Time'], definition:'A very long time.',
      example:'It took ages for the bus to arrive.',
      translation:'uzun zaman, epey vakit', collocations:['for ages','take ages'] },
    { term:'all right/alright', pos:'exclamation', definition:'Said to agree with someone, or to check that they are well.',
      example:'All right, I will meet you at six.',
      translation:'tamam, peki', collocations:['are you all right?'] },
    { term:'as long as', pos:'phrase', definition:'Used to say that one thing will happen only if another is true.',
      example:'You can borrow my bike as long as you bring it back.',
      translation:'-dığı sürece, şartıyla' },
    { term:'as well', pos:'adverb', definition:'In addition to something else.',
      example:'She speaks Italian and a little Greek as well.',
      translation:'de, ayrıca, aynı zamanda', collocations:['as well as'] },
    { term:'at all', pos:'phrase', definition:'Used after a negative to make it stronger.',
      example:'I did not enjoy the film at all.',
      translation:'hiç, hiç de', collocations:['not at all'] },
    { term:'at first', pos:'phrase', definition:'In the beginning, before something changed.',
      example:'At first I thought he was joking.',
      translation:'ilk başta, başlangıçta' },
    { term:'at last', pos:'phrase', definition:'After a long wait, finally.',
      example:'At last the train arrived at the station.',
      translation:'sonunda, nihayet' },
    { term:'at once', pos:'phrase', definition:'Immediately, without waiting.',
      example:'The doctor told him to come in at once.',
      translation:'derhal, hemen' },
    { term:'at present', pos:'phrase', definition:'Now, at this moment in time.',
      example:'We are not hiring anyone at present.',
      translation:'şu anda, halihazırda' },
    { term:'at the same time', pos:'phrase', definition:'During one moment, or used to add another side to an argument.',
      example:'They both started speaking at the same time.',
      translation:'aynı anda, aynı zamanda' },
    { term:'base on', pos:'phrasal verb', definition:'To use something as the starting point for what you make or decide.',
      example:'The film is based on a true story.',
      translation:'dayandırmak, temel almak', collocations:['based on a novel'],
      related:[{kind:'family',text:'basis'},{kind:'family',text:'basic'}] },
    { term:'because of', pos:'phrase', definition:'As a result of a particular thing or person.',
      example:'We stayed at home because of the heavy rain.',
      translation:'yüzünden, nedeniyle, sayesinde' },
    { term:'be over', pos:'phrasal verb', definition:'To have come to an end.',
      example:'The game is over, so we can go home now.',
      translation:'bitmek, sona ermek' },
    { term:'blond', pos:'adjective', definition:'Having pale yellow hair.',
      example:'Her blond hair shone in the summer sun.',
      translation:'sarışın', collocations:['blond hair'],
      related:[{kind:'family',text:'blonde'}] },
    { term:'bookshop', pos:'noun', tags:['Places: Buildings'], definition:'A shop that sells books, as it is called in British English.',
      example:'I bought this novel in a small bookshop near the station.',
      translation:'kitapçı, kitabevi', collocations:['a second-hand bookshop'],
      related:[{kind:'family',text:'book'},{kind:'family',text:'bookseller'}] },
    { term:'bookstore', pos:'noun', tags:['Places: Buildings'], definition:'A shop that sells books, as it is called in American English.',
      example:'There is a large bookstore on Fifth Avenue.',
      translation:'kitapçı, kitabevi', collocations:['an online bookstore'],
      related:[{kind:'family',text:'book'},{kind:'family',text:'bookseller'}] },
    { term:'break in', pos:'phrasal verb', definition:'To enter a building by force, usually in order to steal something.',
      example:'Someone broke in and stole the computer.',
      translation:'zorla girmek', collocations:['break in through a window'],
      related:[{kind:'family',text:'burglar'}] },
    { term:'break up', pos:'phrasal verb', tags:['Education'], definition:'To end a relationship, or to close for the school holidays.',
      example:'When does school break up for the summer?',
      translation:'ayrılmak, tatile girmek', collocations:['break up with someone'] },
    { term:'by accident', pos:'phrase', definition:'Without meaning to do it.',
      example:'I deleted the whole file by accident.',
      translation:'kazara, yanlışlıkla' },
    { term:'by hand', pos:'phrase', definition:'Made or done by a person rather than by a machine.',
      example:'This sweater was knitted by hand.',
      translation:'elde, el ile' },
    { term:'by mistake', pos:'phrase', definition:'When you did not mean to do it.',
      example:'She took my coat by mistake.',
      translation:'yanlışlıkla, sehven' },
    { term:'by name', pos:'phrase', definition:'Using the name of a person or a thing.',
      example:'The teacher knows every pupil by name.',
      translation:'adıyla, ismen' },
    { term:'bye', pos:'exclamation', definition:'Said to someone when you are leaving.',
      example:'Bye, see you tomorrow morning!',
      translation:'hoşça kal, güle güle', collocations:['bye for now'],
      related:[{kind:'syn',text:'goodbye'}] },
    { term:'call for', pos:'phrasal verb', definition:'To go to a place in order to collect someone.',
      example:'I will call for you at seven.',
      translation:'uğrayıp almak, gelip almak' },
    { term:'call in', pos:'phrasal verb', definition:'To visit a place for a short time.',
      example:'She called in to see a friend.',
      translation:'uğramak' },
    { term:'car park', pos:'noun', tags:['Places: Town and City'], definition:'A place where drivers can leave their vehicles.',
      example:'The car park was already full on Saturday morning.',
      translation:'otopark', collocations:['an underground car park'],
      related:[{kind:'family',text:'parking'}] },
    { term:'carry on', pos:'phrasal verb', definition:'To continue doing something.',
      example:'He carried on walking despite the rain.',
      translation:'devam etmek, sürdürmek', collocations:['carry on working'] },
    { term:'carry out', pos:'phrasal verb', definition:'To do something that has been planned or ordered.',
      example:'She carried out the plan according to the instructions.',
      translation:'yerine getirmek, uygulamak', collocations:['carry out a test'] },
    { term:'centimetre', pos:'noun', definition:'A unit of length equal to one hundredth of a metre.',
      example:'The box is thirty centimetres wide.',
      translation:'santimetre',
      related:[{kind:'family',text:'metre'},{kind:'family',text:'millimetre'}] },
    { term:'certainly', pos:'adverb', definition:'Without any doubt.',
      example:'She will certainly pass the exam.',
      translation:'kesinlikle, elbette',
      related:[{kind:'family',text:'certain'},{kind:'family',text:'certainty'}] },
    { term:'chat show', pos:'noun', tags:['Entertainment and Media'], definition:'A television programme where a host talks with famous guests.',
      example:'He was interviewed on a late-night chat show.',
      translation:'söyleşi programı, talk show' },
    { term:'check in', pos:'phrasal verb', tags:['Travel and Transport'], definition:'To report your arrival at a hotel or an airport.',
      example:'They checked in to a hotel near the beach.',
      translation:'giriş yapmak, kayıt yaptırmak', collocations:['check in at the desk'] },
    { term:'check out', pos:'phrasal verb', tags:['Travel and Transport'], definition:'To pay and leave a hotel.',
      example:'He checked out of the hotel on Sunday morning.',
      translation:'çıkış yapmak, otelden ayrılmak' },
    { term:'chill out', pos:'phrasal verb', tags:['Hobbies and Leisure'], definition:'To relax completely after a busy or worrying time.',
      example:'We chilled out on the sofa all evening.',
      translation:'rahatlamak, kafa dinlemek' },
    { term:'come on', pos:'phrasal verb', definition:'To hurry, or said to encourage someone.',
      example:'Come on or we will miss the bus.',
      translation:'hadi gelmek, acele etmek' },
    { term:'congratulations', pos:'exclamation', definition:'Said to someone who has just done something well.',
      example:'Congratulations, you passed the driving test!',
      translation:'tebrikler, tebrik ederim',
      related:[{kind:'family',text:'congratulate'}] },
    { term:'cookie', pos:'noun', tags:['Food and Drink'], definition:'A small flat sweet cake, as it is called in American English.',
      example:'She baked a tray of chocolate cookies.',
      translation:'kurabiye, bisküvi',
      related:[{kind:'syn',text:'biscuit'}] },
    { term:'cool', pos:'exclamation', tags:['Weather'], definition:'Said to show that you think something is very good.',
      example:'Cool, I would love to come with you!',
      translation:'harika, süper' },
    { term:'cross out', pos:'phrasal verb', definition:'To draw a line through writing because it is wrong.',
      example:'Cross out the wrong answer and write it again.',
      translation:'üzerini çizmek, karalamak' },
    { term:'customs', pos:'plural noun', tags:['Travel and Transport'], definition:'The place at a border where officers check what travellers are bringing in.',
      example:'I work as a customs officer at the airport.',
      translation:'gümrük', collocations:['go through customs','a customs officer'] },
    { term:'cut up', pos:'phrasal verb', definition:'To divide something into smaller pieces with a knife.',
      example:'She cut up the cake into small pieces.',
      translation:'doğramak, parçalara ayırmak' },
    { term:'CV', pos:'noun', tags:['Work and Jobs'], definition:'A short written record of your education and work, sent when you apply for a job.',
      example:'Send us your CV and a covering letter.',
      translation:'özgeçmiş', collocations:['write a CV','send a CV'],
      related:[{kind:'syn',text:'resume'}],
      notes:'Short for curriculum vitae.' },
    { term:'date', pos:'noun', tags:['Time'], sense:'a day of the month', definition:'The day of the month or year, written as numbers.',
      example:'What is the date today?',
      translation:'tarih', collocations:['the date of birth','out of date'] },
    { term:'date', pos:'verb', tags:['Time'], definition:'To write the day of the month or year on something.',
      example:'Please sign and date the form at the bottom.',
      translation:'tarih atmak, tarihlendirmek' },
    { term:'dear', pos:'adjective', tags:['Shopping'], definition:'Costing a lot of money, or much loved.',
      example:'That coat is too dear for me to buy.',
      translation:'pahalı, sevgili', collocations:['a dear friend'],
      related:[{kind:'syn',text:'expensive'},{kind:'ant',text:'cheap'}] },
    { term:'dear', pos:'exclamation', tags:['Shopping'], sense:'oh dear', definition:'Said when you are surprised or a little upset.',
      example:'Oh dear, I have forgotten my keys again!',
      translation:'eyvah, aman' },
    { term:'depend', pos:'verb', definition:'To be decided by something else.',
      example:'It depends on what you want to do.',
      translation:'bağlı olmak', collocations:['it depends'],
      related:[{kind:'family',text:'dependent'},{kind:'family',text:'independence'}] },
    { term:'depend', pos:'phrasal verb', sense:'depend on someone', definition:'To trust someone to help you when you need it.',
      example:'You can always depend on your family.',
      translation:'güvenmek, itimat etmek',
      related:[{kind:'syn',text:'rely'},{kind:'family',text:'dependable'}] },
    { term:'dial up', pos:'phrasal verb', tags:['Communications and Technology'], definition:'To connect to the internet using a telephone line.',
      example:'We used to dial up to read our email.',
      translation:'çevirmeli bağlanmak' },
    { term:'disc jockey', pos:'noun', tags:['Entertainment and Media'], definition:'Someone who plays recorded music on the radio or at a party.',
      example:'The disc jockey played dance music until midnight.',
      translation:'diskjokey',
      related:[{kind:'syn',text:'DJ'}] },
    { term:'disco', pos:'noun', tags:['Places: Buildings'], definition:'A place or an event where people dance to recorded music.',
      example:'We danced all night at the school disco.',
      translation:'disko' },
    { term:'DJ', pos:'noun', tags:['Entertainment and Media'], definition:'Someone whose job is playing recorded music for other people.',
      example:'A famous DJ is playing at the club tonight.',
      translation:'diskjokey',
      related:[{kind:'syn',text:'disc jockey'}] },
    { term:'doubt', pos:'noun', definition:'A feeling of not being sure about something.',
      example:'There is some doubt about the price.',
      translation:'şüphe, kuşku', collocations:['no doubt','in doubt'],
      related:[{kind:'family',text:'doubtful'},{kind:'ant',text:'certainty'}] },
    { term:'doubt', pos:'verb', definition:'To feel that something is probably not true or will not happen.',
      example:'I doubt that I will get the job.',
      translation:'şüphe etmek, kuşku duymak',
      related:[{kind:'family',text:'doubtful'}] },
    { term:'driver’s licence', pos:'noun', definition:'An official card showing that you are allowed to drive.',
      example:'The police officer asked to see his driver’s licence.',
      translation:'ehliyet, sürücü belgesi',
      notes:'British English. American English: driver’s license.' },
    { term:'drop', pos:'noun', definition:'A fall in a level or an amount, or a very small round piece of liquid.',
      example:'There has been a drop in prices recently.',
      translation:'düşüş, damla', collocations:['a drop in prices','a drop of water'] },
    { term:'drop', pos:'verb', definition:'To let something fall, or to become lower.',
      example:'I almost dropped the plate on the floor.',
      translation:'düşürmek, azalmak' },
    { term:'drugstore', pos:'noun', definition:'A shop selling medicine and small everyday goods.',
      example:'She bought aspirin at the drugstore on the corner.',
      translation:'eczane',
      notes:'American English. British English: chemist.' },
    { term:'due to', pos:'phrase', definition:'Because of something.',
      example:'The delay was due to heavy snow.',
      translation:'yüzünden, nedeniyle' },
    { term:'dustbin', pos:'noun', tags:['House and Home'], definition:'A large container outside a house for waste.',
      example:'Put the empty bottles in the dustbin.',
      translation:'çöp kutusu, çöp bidonu',
      notes:'British English. American English: trash can.' },
    { term:'elevator', pos:'noun', tags:['Places: Buildings'], definition:'A machine that carries people up and down inside a building.',
      example:'Take the elevator to the ninth floor.',
      translation:'asansör',
      notes:'American English. British English: lift.' },
    { term:'end up', pos:'phrasal verb', definition:'To be in a place or a situation that you did not plan.',
      example:'He plans to end up working in Australia.',
      translation:'varmak, kendini bir yerde bulmak' },
    { term:'eraser', pos:'noun', definition:'A small piece of rubber used to remove pencil marks.',
      example:'May I borrow your eraser for a moment?',
      translation:'silgi',
      notes:'American English. British English: rubber.' },
    { term:'facilities', pos:'plural noun', tags:['Hobbies and Leisure'], definition:'The rooms, equipment and services that a place offers.',
      example:'The hotel has excellent facilities.',
      translation:'olanaklar, tesisler', collocations:['sports facilities'] },
    { term:'fall', pos:'noun', tags:['The Natural World'], definition:'The season between summer and winter, or a drop in an amount.',
      example:'The leaves turn red in the fall.',
      translation:'sonbahar, düşüş', collocations:['a fall in prices'],
      notes:'The season sense is American English. British English: autumn.' },
    { term:'fall', pos:'verb', tags:['The Natural World'], definition:'To drop down towards the ground, or to become lower.',
      example:'Be careful not to fall on the wet floor.',
      translation:'düşmek, azalmak', collocations:['fall asleep','fall in love'] },
    { term:'familiar', pos:'adjective', definition:'Known to you because you have seen or heard it before.',
      example:'Her face looked familiar but I could not remember her name.',
      translation:'tanıdık, aşina', collocations:['familiar with','a familiar face'],
      related:[{kind:'ant',text:'unfamiliar'},{kind:'family',text:'family'}] },
    { term:'fill in', pos:'phrasal verb', definition:'To write the answers in the spaces on a form.',
      example:'You need to fill in a form before the interview.',
      translation:'doldurmak' },
    { term:'fill up', pos:'phrasal verb', definition:'To make something completely full.',
      example:'He filled up the car with petrol.',
      translation:'doldurmak, ağzına kadar doldurmak' },
    { term:'find out', pos:'phrasal verb', definition:'To learn a piece of information for the first time.',
      example:'I must find out when he is arriving.',
      translation:'öğrenmek, bulmak' },
    { term:'first', pos:'adjective', definition:'Coming before all the others.',
      example:'She won first prize in the competition.',
      translation:'ilk, birinci', collocations:['first prize','the first time'],
      related:[{kind:'ant',text:'last'}] },
    { term:'first', pos:'adverb', definition:'Before anything else happens.',
      example:'First of all, let me thank you for coming.',
      translation:'önce, ilkin', collocations:['first of all'] },
    { term:'fit', pos:'adjective', tags:['Clothes and Accessories'], definition:'Healthy and strong, especially from taking exercise.',
      example:'She goes swimming to keep fit.',
      translation:'formda, sağlıklı', collocations:['keep fit'],
      related:[{kind:'family',text:'fitness'},{kind:'ant',text:'unfit'}] },
    { term:'fit', pos:'verb', tags:['Clothes and Accessories'], definition:'To be the right size or shape for someone.',
      example:'These shoes do not fit me any more.',
      translation:'uymak, olmak' },
    { term:'focus on', pos:'verb', definition:'To give all your attention to one thing.',
      example:'Try to focus on one task at a time.',
      translation:'odaklanmak, yoğunlaşmak',
      related:[{kind:'family',text:'focus'}],
      notes:'Also written: focus upon.' },
    { term:'folder', pos:'noun', definition:'A place on a computer where files are kept together, or a cover for papers.',
      example:'Save the picture in the holiday folder.',
      translation:'klasör, dosya' },
    { term:'for sale', pos:'phrase', tags:['Shopping'], definition:'Available to be bought.',
      example:'The house next door is for sale.',
      translation:'satılık' },
    { term:'forward', pos:'adverb', definition:'Towards the front, or towards the future.',
      example:'She stepped forward to shake my hand.',
      translation:'ileri, ileriye', collocations:['look forward to','move forward'],
      related:[{kind:'ant',text:'backward'}] },
    { term:'French fries', pos:'noun', tags:['Food and Drink'], definition:'Long thin pieces of potato cooked in hot oil.',
      example:'He ordered a burger with French fries.',
      translation:'patates kızartması',
      notes:'American English. British English: chips.' },
    { term:'gas', pos:'noun', tags:['Environment'], definition:'A substance like air, or the liquid that makes a car go.',
      example:'We stopped to buy gas before the long drive.',
      translation:'gaz, benzin',
      notes:'The fuel sense is American English. British English: petrol.' },
    { term:'gas station', pos:'noun', tags:['Travel and Transport'], definition:'A place where drivers can buy fuel.',
      example:'There is a gas station just off the motorway.',
      translation:'benzin istasyonu',
      notes:'American English. British English: petrol station.' },
    { term:'get along', pos:'phrasal verb', definition:'To have a friendly relationship with someone.',
      example:'How do you get along with Harry?',
      translation:'geçinmek, anlaşmak' },
    { term:'get back', pos:'phrasal verb', definition:'To return to a place.',
      example:'When did you get back from New York?',
      translation:'dönmek, geri gelmek' },
    { term:'get in', pos:'phrasal verb', definition:'To enter a place or a small vehicle.',
      example:'Can you get in through the window?',
      translation:'girmek, binmek' },
    { term:'get off', pos:'phrasal verb', definition:'To leave a bus, a train or a plane.',
      example:'We get off at the next stop.',
      translation:'inmek' },
    { term:'get rid of', pos:'phrasal verb', definition:'To throw away or remove something you no longer want.',
      example:'Have you got rid of those old documents?',
      translation:'kurtulmak, başından atmak' },
    { term:'get up', pos:'phrasal verb', definition:'To leave your bed in the morning.',
      example:'What time do you get up in the morning?',
      translation:'kalkmak, yataktan kalkmak' },
    { term:'give back', pos:'phrasal verb', definition:'To return something to the person who owns it.',
      example:'Please give back this book on Tuesday.',
      translation:'geri vermek, iade etmek' },
    { term:'give out', pos:'phrasal verb', definition:'To hand something to each person in a group.',
      example:'Will you give out these papers for me, please?',
      translation:'dağıtmak' },
    { term:'give way', pos:'phrasal verb', definition:'To let other traffic go before you.',
      example:'You must give way to traffic at a roundabout.',
      translation:'yol vermek' },
    { term:'glasses', pos:'plural noun', tags:['Clothes and Accessories'], definition:'Two pieces of shaped glass in a frame, worn to see better.',
      example:'He put on his glasses to read the small print.',
      translation:'gözlük', collocations:['a pair of glasses','reading glasses'] },
    { term:'get down', pos:'phrasal verb', definition:'To move to a lower position, or to write something you hear.',
      example:'Get down at once, that ladder is not safe!',
      translation:'inmek, not almak' },
    { term:'get on', pos:'phrasal verb', definition:'To climb onto a bus or a train, or to make progress.',
      example:'How are you getting on in your new job?',
      translation:'binmek, ilerlemek' },
    { term:'give in', pos:'phrasal verb', definition:'To hand work to a teacher, or to stop trying to win.',
      example:'Have you given in your homework yet?',
      translation:'teslim etmek, pes etmek' },
    { term:'go for', pos:'phrasal verb', definition:'To try to get something, or to attack someone.',
      example:'He went for the job and got it.',
      translation:'peşinden gitmek, saldırmak' },
    { term:'good afternoon', pos:'exclamation', definition:'Said when you meet someone in the middle of the day.',
      example:'Good afternoon, please take a seat.',
      translation:'tünaydın, iyi günler' },
    { term:'goodbye', pos:'exclamation', definition:'Said to someone who is leaving, or when you leave.',
      example:'We said goodbye at the station.',
      translation:'hoşça kal, güle güle',
      related:[{kind:'syn',text:'bye'}] },
    { term:'good evening', pos:'exclamation', definition:'Said when you meet someone late in the day.',
      example:'Good evening, your table is ready.',
      translation:'iyi akşamlar' },
    { term:'good morning', pos:'exclamation', definition:'Said when you meet someone early in the day.',
      example:'Good morning, did you sleep well?',
      translation:'günaydın' },
    { term:'good night', pos:'exclamation', definition:'Said when you leave someone in the evening or go to bed.',
      example:'Good night, see you in the morning.',
      translation:'iyi geceler' },
    { term:'goods', pos:'plural noun', tags:['Language'], definition:'Things that are made to be sold.',
      example:'The lorry was carrying electrical goods.',
      translation:'mallar, eşya', collocations:['electrical goods','a goods train'] },
    { term:'go off', pos:'phrasal verb', definition:'To leave a place, or to stop working, or to make a sudden loud noise.',
      example:'Suddenly the lights went off in the whole street.',
      translation:'gitmek, sönmek, çalmak' },
    { term:'go on', pos:'phrasal verb', definition:'To continue, or to happen.',
      example:'The meeting went on until six o’clock.',
      translation:'devam etmek, sürmek' },
    { term:'go out', pos:'phrasal verb', tags:['Hobbies and Leisure'], definition:'To leave your home for the evening, or to stop burning.',
      example:'Are you going out this evening?',
      translation:'dışarı çıkmak, sönmek' },
    { term:'go', pos:'phrasal verb', tags:['Clothes and Accessories'], sense:'go with', definition:'To look good together with something else.',
      example:'Your tie does not go with your shirt.',
      translation:'yakışmak, uymak' },
    { term:'gram', pos:'noun', definition:'A unit of weight equal to one thousandth of a kilogram.',
      example:'Add two hundred grams of sugar to the bowl.',
      translation:'gram', sameInTurkish:true,
      related:[{kind:'family',text:'kilogram'}],
      notes:'Also written: gramme.' },
    { term:'grandad', pos:'noun', definition:'The father of your mother or father, spoken of informally.',
      example:'My grandad taught me how to fish.',
      translation:'dede, büyükbaba',
      related:[{kind:'syn',text:'grandfather'}],
      notes:'Also written: granddad.' },
    { term:'graphics', pos:'plural noun', definition:'Pictures and designs, especially ones made on a computer.',
      example:'The graphics in this game are very realistic.',
      translation:'grafikler',
      related:[{kind:'family',text:'graph'}] },
    { term:'grey', pos:'adjective', tags:['Colours'], definition:'Of the colour between black and white.',
      example:'He wore a grey suit to the wedding.',
      translation:'gri', collocations:['grey hair','a grey sky'],
      notes:'British English. American English: gray.' },
    { term:'grey', pos:'noun', tags:['Colours'], definition:'The colour between black and white.',
      example:'She always paints the walls in grey.',
      translation:'gri',
      notes:'British English. American English: gray.' },
    { term:'grocery store', pos:'noun', definition:'A shop that sells food and things for the home.',
      example:'I buy milk at the grocery store on my way home.',
      translation:'bakkal, market',
      notes:'American English. British English: grocer’s.' },
    { term:'grow up', pos:'phrasal verb', definition:'To become older and change from a child into an adult.',
      example:'Children grow up fast.',
      translation:'büyümek, yetişmek' },
    { term:'hand in', pos:'phrasal verb', definition:'To give a piece of work to a teacher or an official.',
      example:'Please hand in the answer sheet when you have finished.',
      translation:'teslim etmek' },
    { term:'hand out', pos:'phrasal verb', definition:'To give one of something to each person in a group.',
      example:'Hand out the books please, Tom.',
      translation:'dağıtmak' },
    { term:'hang out', pos:'phrasal verb', tags:['Hobbies and Leisure'], definition:'To spend time somewhere with friends, doing nothing special.',
      example:'They like to hang out at the shopping centre.',
      translation:'takılmak, vakit geçirmek' },
    { term:'hang up', pos:'phrasal verb', tags:['Communications and Technology'], definition:'To end a telephone call.',
      example:'She hung up at the end of the phone call.',
      translation:'telefonu kapatmak' },
    { term:'hello', pos:'exclamation', definition:'Said when you meet someone or answer the telephone.',
      example:'Hello, how are you today?',
      translation:'merhaba, alo',
      related:[{kind:'syn',text:'hi'}] },
    { term:'hey', pos:'exclamation', definition:'Said to get someone’s attention, or to show surprise.',
      example:'Hey, wait for me!',
      translation:'hey, baksana', sameInTurkish:true },
    { term:'hi', pos:'exclamation', definition:'A friendly greeting used between people who know each other.',
      example:'Hi, it is good to see you again.',
      translation:'selam, merhaba',
      related:[{kind:'syn',text:'hello'}] },
    { term:'hire', pos:'verb', tags:['Hobbies and Leisure'], definition:'To pay to use something for a short time, or to give someone a job.',
      example:'We decided to hire a boat for the afternoon.',
      translation:'kiralamak, işe almak',
      related:[{kind:'syn',text:'rent'}] },
    { term:'hire', pos:'noun', tags:['Hobbies and Leisure'], definition:'The paying of money to use something for a short time.',
      example:'The bikes are available for hire by the hour.',
      translation:'kiralama', collocations:['for hire','car hire'] },
    { term:'hit', pos:'noun', tags:['Sport'], definition:'Something very popular and successful, especially a song or a film.',
      example:'The song was a great hit last summer.',
      translation:'hit, gözde şarkı', collocations:['a big hit'] },
    { term:'hit', pos:'verb', tags:['Sport'], definition:'To touch someone or something quickly and hard.',
      example:'She hit the ball over the net.',
      translation:'vurmak, çarpmak' },
    { term:'hold up', pos:'phrasal verb', definition:'To make someone or something late.',
      example:'He was held up in heavy traffic for two hours.',
      translation:'geciktirmek, oyalamak' },
    { term:'identity card', pos:'noun', definition:'An official card showing who you are, with your photograph on it.',
      example:'Show your identity card at the door.',
      translation:'kimlik kartı',
      related:[{kind:'syn',text:'ID'}] },
    { term:'impressed', pos:'adjective', tags:['Language'], definition:'Admiring someone or something because they are very good.',
      example:'We were impressed by her clear answers.',
      translation:'etkilenmiş', collocations:['impressed by','impressed with'],
      related:[{kind:'family',text:'impress'},{kind:'family',text:'impressive'}] },
    { term:'in advance', pos:'phrase', definition:'Before something happens.',
      example:'You must book the tickets in advance.',
      translation:'önceden, peşin' },
    { term:'in fact', pos:'phrase', definition:'Used to add something true that may be surprising.',
      example:'He looks young, but in fact he is fifty.',
      translation:'aslında, hatta' },
    { term:'in front of', pos:'phrase', definition:'At the part of something that faces forward, or before someone.',
      example:'A tall man sat in front of me at the cinema.',
      translation:'önünde',
      related:[{kind:'ant',text:'behind'}] },
    { term:'in half', pos:'phrase', definition:'Into two equal pieces.',
      example:'She cut the apple in half.',
      translation:'ikiye, yarı yarıya' },
    { term:'in ink', pos:'phrase', definition:'Written with a pen rather than a pencil.',
      example:'Please write your answers in ink.',
      translation:'mürekkeple, kalemle' },
    { term:'in love', pos:'phrase', definition:'Feeling a strong romantic attraction to someone.',
      example:'They fell in love on holiday.',
      translation:'aşık', collocations:['fall in love','in love with'] },
    { term:'in pencil', pos:'phrase', definition:'Written with a pencil so that it can be rubbed out.',
      example:'Draw the lines in pencil first.',
      translation:'kurşun kalemle' },
    { term:'in order', pos:'phrase', definition:'Arranged one after another in the right way.',
      example:'Put the pictures in order from oldest to newest.',
      translation:'sırayla, düzenli' },
    { term:'in order to', pos:'phrase', definition:'With the purpose of doing something.',
      example:'She left early in order to catch the train.',
      translation:'-mek için, amacıyla' },
    { term:'instead', pos:'adverb', definition:'In the place of someone or something else.',
      example:'There were no lemons so I bought oranges instead.',
      translation:'yerine, onun yerine', collocations:['instead of'] },
    { term:'instructions', pos:'plural noun', tags:['Education'], definition:'Words telling you how to do something or how to use a thing.',
      example:'Read the instructions before you start the exam.',
      translation:'talimatlar, yönerge', collocations:['follow the instructions'],
      related:[{kind:'family',text:'instruct'},{kind:'family',text:'instructor'}] },
    { term:'in the end', pos:'phrase', definition:'After a lot of time or trouble, finally.',
      example:'In the end we decided to stay at home.',
      translation:'sonunda, en sonunda' },
    { term:'in time', pos:'phrase', definition:'Early enough for something.',
      example:'We arrived in time for the first song.',
      translation:'vaktinde, zamanında' },
    { term:'in two', pos:'phrase', definition:'Into two separate pieces.',
      example:'The plate fell and broke in two.',
      translation:'ikiye, iki parçaya' },
    { term:'IT', pos:'noun', tags:['Education'], definition:'The study and use of computers for storing and sending information.',
      example:'She works in IT at a large bank.',
      translation:'bilişim, bilgi teknolojisi',
      notes:'Short for information technology.' },
    { term:'jail', pos:'noun', definition:'A building where criminals are kept as a punishment.',
      example:'He spent two years in jail.',
      translation:'hapishane, cezaevi',
      notes:'American English. British English: prison.' },
    { term:'jeans', pos:'plural noun', tags:['Clothes and Accessories'], definition:'Trousers made of strong cotton cloth, usually blue.',
      example:'She wore jeans and a white shirt.',
      translation:'kot pantolon', collocations:['a pair of jeans'] },
    { term:'jewellery', pos:'noun', tags:['Clothes and Accessories'], definition:'Rings, necklaces and other pretty things worn on the body.',
      example:'She keeps her jewellery in a wooden box.',
      translation:'mücevher, takı',
      notes:'British English. American English: jewelry.' },
    { term:'keep in', pos:'phrasal verb', definition:'To make someone stay indoors.',
      example:'She kept the children in as it was so cold.',
      translation:'içeride tutmak' },
    { term:'keep on', pos:'phrasal verb', definition:'To continue doing something without stopping.',
      example:'He kept on talking for an hour.',
      translation:'devam etmek, sürdürmek' }
  ]
};
