/* One hundred cards written by hand, for comparison.

   These are the first hundred words in the generator's queue — the same words,
   in the same order, that the model was given first. They are kept apart from
   the deck on purpose: the point is to be able to read the two side by side
   and decide, word by word, which card is better. Whichever wins goes into
   deck-b1.js; this file is the record of what the comparison was.

   Checked against the same rules as the deck itself.                        */
module.exports = [
{ term:'ability', pos:'noun', definition:'The power or skill needed to do something.',
  example:'She has the ability to learn quickly.',
  translation:'yetenek, kabiliyet, beceri', collocations:['the ability to'],
  related:[{kind:'ant',text:'inability'},{kind:'family',text:'able'}] },
{ term:'about', pos:'adverb', definition:'A little more or a little less than a number.',
  example:'There were about five hundred students.',
  translation:'yaklaşık, aşağı yukarı' },
{ term:'above', pos:'adjective', definition:'Written or shown earlier on the same page.',
  example:'Please read the above sentence carefully.',
  translation:'yukarıdaki' },
{ term:'above', pos:'adverb', definition:'In a higher position.',
  example:'The birds circled high above.',
  translation:'yukarıda, üstte', related:[{kind:'ant',text:'below'}] },
{ term:'abroad', pos:'adverb', definition:'In or to a foreign country.',
  example:'They went abroad for the summer.',
  translation:'yurt dışında, yurt dışına', collocations:['go abroad','live abroad'] },
{ term:'absent', pos:'adjective', definition:'Not in the place where you are expected to be.',
  example:'Three students were absent from the lesson.',
  translation:'yok, devamsız', related:[{kind:'ant',text:'present'},{kind:'family',text:'absence'}] },
{ term:'accept', pos:'verb', definition:'To agree to take something that is offered.',
  example:'She accepted the job without hesitating.',
  translation:'kabul etmek', related:[{kind:'ant',text:'refuse'},{kind:'family',text:'acceptable'}] },
{ term:'acceptable', pos:'adjective', definition:'Good enough, though not excellent.',
  example:'Your work is acceptable but could be better.',
  translation:'kabul edilebilir, uygun', related:[{kind:'ant',text:'unacceptable'},{kind:'family',text:'accept'}] },
{ term:'accommodation', pos:'noun', definition:'A place for someone to live or to stay.',
  example:'The price includes accommodation and breakfast.',
  translation:'konaklama, kalacak yer' },
{ term:'accompany', pos:'verb', definition:'To go somewhere with someone.',
  example:'A teacher will accompany the children on the trip.',
  translation:'eşlik etmek' },
{ term:'account', pos:'noun', definition:'An arrangement with a bank for keeping your money.',
  example:'She opened a bank account last week.',
  translation:'hesap', collocations:['a bank account','open an account'] },
{ term:'accountant', pos:'noun', definition:'Someone whose job is keeping the money records of a business.',
  example:'The accountant checked every receipt.',
  translation:'muhasebeci', related:[{kind:'family',text:'account'}] },
{ term:'accurate', pos:'adjective', definition:'Correct in every detail.',
  example:'The clock is not very accurate.',
  translation:'doğru, isabetli', related:[{kind:'ant',text:'inaccurate'}] },
{ term:'ache', pos:'noun', definition:'A pain that continues for a long time.',
  example:'She had a bad ache in her back.',
  translation:'ağrı, sızı', collocations:['a stomach ache','aches and pains'] },
{ term:'achievement', pos:'noun', definition:'Something important that you succeed in doing.',
  example:'Winning the prize was a great achievement.',
  translation:'başarı', related:[{kind:'family',text:'achieve'}] },
{ term:'across', pos:'adverb', definition:'From one side to the other.',
  example:'The river is too wide to swim across.',
  translation:'karşıdan karşıya, öbür tarafa' },
{ term:'action', pos:'noun', definition:'Something that someone does.',
  example:'The film is full of action.',
  translation:'hareket, eylem', collocations:['take action'], related:[{kind:'family',text:'act'}] },
{ term:'active', pos:'adjective', definition:'Busy doing things, or moving a lot.',
  example:'My grandmother is still very active.',
  translation:'hareketli, faal', related:[{kind:'family',text:'activity'},{kind:'ant',text:'inactive'}] },
{ term:'activity', pos:'noun', definition:'Something that people do, especially for enjoyment.',
  example:'Swimming is my favourite activity.',
  translation:'etkinlik, faaliyet', related:[{kind:'family',text:'active'}] },
{ term:'actor', pos:'noun', definition:'Someone who performs in a play or a film.',
  example:'The actor forgot his lines.',
  translation:'aktör, oyuncu', related:[{kind:'family',text:'act'},{kind:'family',text:'actress'}] },
{ term:'actress', pos:'noun', definition:'A woman who performs in a play or a film.',
  example:'The actress won an award for the role.',
  translation:'aktris, kadın oyuncu', related:[{kind:'family',text:'actor'}] },
{ term:'add', pos:'verb', definition:'To put something with something else, or to put numbers together.',
  example:'Add a little salt to the soup.',
  translation:'eklemek, toplamak', related:[{kind:'family',text:'addition'}] },
{ term:'addition', pos:'noun', definition:'Something put with something else, or the putting together of numbers.',
  example:'In addition, the price includes breakfast.',
  translation:'ekleme, toplama', collocations:['in addition'], related:[{kind:'family',text:'add'}] },
{ term:'address', pos:'noun', definition:'The details of where a person lives or where a letter must go.',
  example:'Write your address on the form.',
  translation:'adres', collocations:['an email address','a home address'] },
{ term:'admission', pos:'noun', definition:'The right to enter a place, or the money paid to enter.',
  example:'Admission to the museum is free.',
  translation:'giriş, giriş ücreti', collocations:['admission charges'] },
{ term:'admit', pos:'verb', definition:'To agree that something bad is true.',
  example:'He admitted that he had made a mistake.',
  translation:'itiraf etmek, kabul etmek', related:[{kind:'family',text:'admission'}] },
{ term:'adult', pos:'adjective', definition:'Fully grown, or meant for grown people only.',
  example:'The film is for an adult audience.',
  translation:'yetişkin' },
{ term:'adult', pos:'noun', definition:'A person who is fully grown.',
  example:'Two adults and one child, please.',
  translation:'yetişkin', related:[{kind:'ant',text:'child'}] },
{ term:'advance', pos:'noun', definition:'Forward movement, or money paid before it is due.',
  example:'Book the tickets in advance.',
  translation:'ilerleme, avans', collocations:['in advance'] },
{ term:'advanced', pos:'adjective', definition:'At a high level, past the early stages.',
  example:'She joined an advanced Spanish class.',
  translation:'ileri, ileri düzey', related:[{kind:'ant',text:'elementary'}] },
{ term:'advantage', pos:'noun', definition:'Something that helps you do better than others.',
  example:'Speaking two languages is a real advantage.',
  translation:'avantaj, üstünlük', related:[{kind:'ant',text:'disadvantage'}] },
{ term:'adventure', pos:'noun', definition:'An exciting and sometimes dangerous experience.',
  example:'The holiday turned into a real adventure.',
  translation:'macera', related:[{kind:'family',text:'adventurous'}] },
{ term:'advert', pos:'noun', definition:'A short public notice that tries to sell something.',
  example:'I saw an advert for the concert.',
  translation:'reklam, ilan', related:[{kind:'family',text:'advertise'}] },
{ term:'advertise', pos:'verb', definition:'To tell people about a product so that they will buy it.',
  example:'They advertise the shop on local radio.',
  translation:'reklam yapmak, ilan vermek', related:[{kind:'family',text:'advert'}] },
{ term:'advertisement', pos:'noun', definition:'A public notice that tries to sell something or offer a job.',
  example:'The advertisement appeared in the local paper.',
  translation:'reklam, ilan', related:[{kind:'family',text:'advertise'}] },
{ term:'aeroplane', pos:'noun', definition:'A vehicle with wings that flies through the sky.',
  example:'The aeroplane landed exactly on time.',
  translation:'uçak', notes:'British English. American English: airplane.' },
{ term:'affect', pos:'verb', definition:'To cause a change in someone or something.',
  example:'The weather can affect your mood.',
  translation:'etkilemek' },
{ term:'afraid', pos:'adjective', definition:'Feeling fear or worry.',
  example:'She is afraid of large dogs.',
  translation:'korkmuş, endişeli', collocations:['afraid of'], related:[{kind:'syn',text:'scared'}] },
{ term:'after', pos:'adverb', definition:'Later than something else.',
  example:'We had coffee and a short walk after.',
  translation:'sonra, ardından', related:[{kind:'ant',text:'before'}] },
{ term:'afternoon', pos:'noun', definition:'The part of the day between noon and evening.',
  example:'We play tennis on Sunday afternoon.',
  translation:'öğleden sonra', collocations:['in the afternoon'] },
{ term:'afterwards', pos:'adverb', definition:'At a later time than something already mentioned.',
  example:'We had dinner and went home afterwards.',
  translation:'sonradan, daha sonra' },
{ term:'again', pos:'adverb', definition:'One more time.',
  example:'Please say that again more slowly.',
  translation:'tekrar, yine', collocations:['once again','again and again'] },
{ term:'age', pos:'noun', definition:'How old someone or something is.',
  example:'Children under the age of five travel free.',
  translation:'yaş', collocations:['at the age of'] },
{ term:'aged', pos:'adjective', definition:'Having lived for a particular number of years.',
  example:'A boy aged twelve won the race.',
  translation:'yaşında' },
{ term:'agency', pos:'noun', definition:'A business that arranges things for other people.',
  example:'We booked the trip through a travel agency.',
  translation:'acente, ajans', collocations:['a travel agency'] },
{ term:'ago', pos:'adverb', definition:'In the past, before now.',
  example:'They moved here three years ago.',
  translation:'önce' },
{ term:'agree', pos:'verb', definition:'To have the same opinion, or to say yes to a plan.',
  example:'We all agree with your idea.',
  translation:'katılmak, aynı fikirde olmak', collocations:['agree with','agree to'],
  related:[{kind:'ant',text:'disagree'},{kind:'family',text:'agreement'}] },
{ term:'ahead', pos:'adverb', definition:'In front, or in the future.',
  example:'The road ahead was completely empty.',
  translation:'ileride, önde', collocations:['go ahead','ahead of'] },
{ term:'aim', pos:'noun', definition:'Something that you are trying to do.',
  example:'Our main aim is to finish today.',
  translation:'amaç, hedef', related:[{kind:'syn',text:'goal'}] },
{ term:'aim', pos:'verb', definition:'To plan to do something, or to point a weapon at a target.',
  example:'They aim to open the shop in May.',
  translation:'amaçlamak, nişan almak' },
{ term:'air', pos:'noun', definition:'The mixture of gases around us that we breathe.',
  example:'The air was cold and clean.',
  translation:'hava', collocations:['fresh air','by air'] },
{ term:'air conditioning', pos:'noun', definition:'A system that keeps the rooms of a building cool.',
  example:'The hotel has air conditioning in every room.',
  translation:'klima' },
{ term:'air force', pos:'noun', definition:'The part of a country’s military that fights in the sky.',
  example:'Her father served in the air force.',
  translation:'hava kuvvetleri' },
{ term:'airline', pos:'noun', definition:'A company that carries passengers by plane.',
  example:'The airline lost my suitcase.',
  translation:'havayolu şirketi' },
{ term:'airport', pos:'noun', definition:'A place where planes take off and land.',
  example:'We arrived at the airport two hours early.',
  translation:'havalimanı, havaalanı' },
{ term:'alarm', pos:'noun', definition:'A loud sound that warns people of danger.',
  example:'The fire alarm rang during the lesson.',
  translation:'alarm', sameInTurkish:true, collocations:['a fire alarm'] },
{ term:'alarm clock', pos:'noun', definition:'A clock that makes a sound to wake you.',
  example:'My alarm clock did not ring this morning.',
  translation:'çalar saat' },
{ term:'album', pos:'noun', definition:'A collection of songs, or a book for photographs.',
  example:'The band released a new album.',
  translation:'albüm' },
{ term:'alike', pos:'adverb', definition:'In the same way, or similar to each other.',
  example:'The twins dress alike every day.',
  translation:'benzer şekilde, aynı' },
{ term:'alive', pos:'adjective', definition:'Living, not dead.',
  example:'The fish was still alive in the net.',
  translation:'canlı, hayatta', related:[{kind:'ant',text:'dead'}] },
{ term:'all', pos:'adjective', definition:'Every one of a group, or the whole of something.',
  example:'All the children were tired.',
  translation:'bütün, tüm', collocations:['all day','all the time'] },
{ term:'all', pos:'adverb', definition:'Completely.',
  example:'She was dressed all in black.',
  translation:'tamamen' },
{ term:'all right/alright', pos:'adjective', definition:'Good enough, or not hurt.',
  example:'Are you all right after the fall?',
  translation:'iyi, sorunsuz' },
{ term:'all right/alright', pos:'adverb', definition:'In a way that is good enough.',
  example:'The car runs all right on cold mornings.',
  translation:'iyi, idare eder şekilde' },
{ term:'allow', pos:'verb', definition:'To let someone do something.',
  example:'They do not allow dogs in the park.',
  translation:'izin vermek', related:[{kind:'ant',text:'forbid'}] },
{ term:'almost', pos:'adverb', definition:'Very nearly but not completely.',
  example:'I almost missed the train.',
  translation:'neredeyse', related:[{kind:'syn',text:'nearly'}] },
{ term:'alone', pos:'adverb', definition:'Without other people.',
  example:'She travelled alone across Europe.',
  translation:'tek başına, yalnız' },
{ term:'alone', pos:'adjective', definition:'Without anyone else present.',
  example:'He was alone in the empty house.',
  translation:'yalnız', related:[{kind:'syn',text:'lonely'}] },
{ term:'along', pos:'adverb', definition:'Forward, or together with someone.',
  example:'Bring your sister along to the party.',
  translation:'birlikte, beraberinde' },
{ term:'aloud', pos:'adverb', definition:'In a voice that others can hear.',
  example:'Please read the poem aloud.',
  translation:'sesli, yüksek sesle', collocations:['read aloud'] },
{ term:'alphabet', pos:'noun', definition:'All the letters of a language in their usual order.',
  example:'The Greek alphabet has twenty-four letters.',
  translation:'alfabe', related:[{kind:'family',text:'alphabetical'}] },
{ term:'already', pos:'adverb', definition:'Before now, or sooner than expected.',
  example:'They have already finished the work.',
  translation:'çoktan, zaten' },
{ term:'also', pos:'adverb', definition:'In addition.',
  example:'She speaks French and also Italian.',
  translation:'ayrıca, de', related:[{kind:'syn',text:'too'}] },
{ term:'altogether', pos:'adverb', definition:'In total, or completely.',
  example:'That comes to twenty pounds altogether.',
  translation:'toplamda, tamamen' },
{ term:'always', pos:'adverb', definition:'Every time, or at all times.',
  example:'He always arrives before eight.',
  translation:'her zaman, daima', related:[{kind:'ant',text:'never'}] },
{ term:'a.m.', pos:'adverb', definition:'In the hours between midnight and midday.',
  example:'My train leaves at six a.m.',
  translation:'öğleden önce', related:[{kind:'ant',text:'p.m.'}] },
{ term:'amazed', pos:'adjective', definition:'Very surprised.',
  example:'We were amazed by the size of the building.',
  translation:'hayret etmiş, şaşkın', related:[{kind:'family',text:'amaze'}] },
{ term:'amazing', pos:'adjective', definition:'So good or surprising that it is hard to believe.',
  example:'The view from the top is amazing.',
  translation:'harika, şaşırtıcı', related:[{kind:'family',text:'amaze'}] },
{ term:'ambition', pos:'noun', definition:'Something you want very much to achieve.',
  example:'Her ambition is to become a doctor.',
  translation:'hedef, tutku', related:[{kind:'family',text:'ambitious'}] },
{ term:'ambulance', pos:'noun', definition:'A vehicle that takes ill people to hospital.',
  example:'The ambulance arrived within ten minutes.',
  translation:'ambulans' },
{ term:'amount', pos:'noun', definition:'How much there is of something.',
  example:'A large amount of money was collected.',
  translation:'miktar', collocations:['a large amount of'] },
{ term:'amusing', pos:'adjective', definition:'Funny in a gentle way.',
  example:'He told an amusing story about his cat.',
  translation:'eğlenceli, komik', related:[{kind:'family',text:'amuse'}] },
{ term:'angry', pos:'adjective', definition:'Feeling strong displeasure.',
  example:'She was angry about the broken window.',
  translation:'kızgın, öfkeli', collocations:['angry with','angry about'],
  related:[{kind:'family',text:'anger'}] },
{ term:'animal', pos:'noun', definition:'A living thing that can move, such as a dog or a bird.',
  example:'My favourite animal is the elephant.',
  translation:'hayvan', collocations:['a wild animal'] },
{ term:'ankle', pos:'noun', definition:'The joint between the foot and the leg.',
  example:'She hurt her ankle while running.',
  translation:'ayak bileği' },
{ term:'anniversary', pos:'noun', definition:'A day when you remember something that happened on the same date.',
  example:'They celebrated their tenth wedding anniversary.',
  translation:'yıldönümü', collocations:['a wedding anniversary'] },
{ term:'announcement', pos:'noun', definition:'A public statement that gives people information.',
  example:'There was an announcement about the delayed flight.',
  translation:'duyuru, anons', related:[{kind:'family',text:'announce'}] },
{ term:'annoy', pos:'verb', definition:'To make someone slightly angry.',
  example:'The noise from the street began to annoy me.',
  translation:'kızdırmak, rahatsız etmek', related:[{kind:'family',text:'annoyance'}] },
{ term:'annual', pos:'adjective', definition:'Happening once every year.',
  example:'The club holds an annual dinner.',
  translation:'yıllık', collocations:['an annual report'] },
{ term:'answerphone', pos:'noun', definition:'A machine that records messages when you cannot take a call.',
  example:'Leave a message on the answerphone.',
  translation:'telesekreter' },
{ term:'ant', pos:'noun', definition:'A very small insect that lives in large groups.',
  example:'An ant carried the crumb away.',
  translation:'karınca' },
{ term:'antique', pos:'adjective', definition:'Old and valuable because it was made long ago.',
  example:'They bought an antique clock.',
  translation:'antika' },
{ term:'antique', pos:'noun', definition:'An old object that is valuable because it is rare.',
  example:'The table is a genuine antique.',
  translation:'antika' },
{ term:'anxious', pos:'adjective', definition:'Worried about something that may happen.',
  example:'She felt anxious before the interview.',
  translation:'endişeli, kaygılı', related:[{kind:'family',text:'anxiety'}] },
{ term:'anymore', pos:'adverb', definition:'No longer, from this time on.',
  example:'He does not live here anymore.',
  translation:'artık' },
{ term:'anyway', pos:'adverb', definition:'Despite that, or used when changing the subject.',
  example:'It was raining, but we went anyway.',
  translation:'yine de, her neyse' },
{ term:'anywhere', pos:'adverb', definition:'In or to any place.',
  example:'I cannot find my glasses anywhere.',
  translation:'hiçbir yerde, herhangi bir yerde' },
{ term:'apart', pos:'adverb', definition:'Separated by a distance or by time.',
  example:'The two houses stand fifty metres apart.',
  translation:'ayrı, uzak' },
{ term:'apart from', pos:'adverb', definition:'Except for, or in addition to.',
  example:'Everyone came apart from Sara.',
  translation:'dışında, hariç' },
{ term:'apartment', pos:'noun', definition:'A set of rooms for living in, on one floor of a building.',
  example:'They rent a small apartment near the park.',
  translation:'daire, apartman dairesi',
  notes:'American English. British English: flat.' }
];
